---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: turnos-vtv-periodic-task
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: periodic-task
            image: registry.home/turnos-vtv:latest
            command: ["python", "periodic.py"]
            env:
            - name: TELEGRAM_BOT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: telegram-bot-secrets
                  key: TELEGRAM_BOT_API_KEY
            - name: LOG_LEVEL
              value: "INFO"
            - name: DATABASE_PATH
              value: "/app/data/vtv_turnos.db"
            volumeMounts:
            - name: sqlite-storage
              mountPath: /app/data
          volumes:
          - name: sqlite-storage
            persistentVolumeClaim:
              claimName: sqlite-pvc
          restartPolicy: OnFailure